# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f4436b8a5584e7c32e8281779d6acc525276fc114d388a32a0c87e4dae87dc34fc63d8c48ec1bd28e2ccd323ffb87b65425fc7399f728ab2a32e2c73be0a600

test:
  secret_key_base: 4aafb681fa546cc736a9b82ee0dc1e26f667f97658ba2d5b7d9bc00db936fdc40dd81f437a6edbbdf1118b470a4a5f4175b91801104b334efedc3a6157863a35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
